### ISSUE TITLE
Typestring Parser errors on getNodeType

### ISSUE THREAD

**Issue by LuisLara-UH** [Consensys/solc-typed-ast#161]
I am using the version 10.3.0 of solc-typed-ast

I am compiling the following contracts:

```
contract A {
    function x() public pure returns (string memory) {
        return '"a"'; 
    }
}

```
```
contract B {
    function x() public pure returns (string memory) {
        return '\\'; 
    }
}

```
And I am trying to [get the NodeTypes](https://github.com/ConsenSys/solc-typed-ast/blob/master/src/types/typeStrings/typeString_parser_header.ts#L108) of the corresponding nodes of strings `'"a"'` and `'\\'`

For string `'"a"'`, I get this parsing error:
```
SyntaxError: Expected "[", "calldata", "memory", "storage", [\n,\r, , ], end of input, or whitespace but "a" found.
    at peg$buildStructuredError (/Users/luisalejandrolararojas/Documents/GitHub/warp/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:656:16)
    at peg$parse (/Users/luisalejandrolararojas/Documents/GitHub/warp/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:5340:15)
    at getNodeType (/Users/luisalejandrolararojas/Documents/GitHub/warp/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:59:30)
    at ...
expected: [
    { type: 'other', description: 'whitespace' },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '[', ignoreCase: false },
    { type: 'literal', text: 'memory', ignoreCase: false },
    { type: 'literal', text: 'storage', ignoreCase: false },
    { type: 'literal', text: 'calldata', ignoreCase: false },
    { type: 'end' }
  ],
  found: 'a',
  location: {
    source: undefined,
    start: { offset: 17, line: 1, column: 18 },
    end: { offset: 18, line: 1, column: 19 }
  }
```
This is the raw value of the string node `'"a"'` in the AST:
```
    hexValue: '226122',
    id: 6,
    isConstant: false,
    isLValue: false,
    isPure: true,
    kind: 'string',
    lValueRequested: false,
    nodeType: 'Literal',
    src: '154:5:0',
    typeDescriptions: {
      typeIdentifier: 't_stringliteral_660c9a8d0051d07b1abd38e8a6f68076d98fdf948abd2a13e2870fe08a1343cc',
      typeString: 'literal_string ""a""'
    },
    value: '"a"'
```

For the string `'\\'` I am getting the following parsing error:
```
SyntaxError: Expected "\"", "\\", or any character but end of input found.
    at peg$buildStructuredError (/Users/luisalejandrolararojas/Documents/GitHub/warp/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:656:16)
    at peg$parse (/Users/luisalejandrolararojas/Documents/GitHub/warp/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:5340:15)
    at getNodeType (/Users/luisalejandrolararojas/Documents/GitHub/warp/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:59:30)
    at ...
expected: [
    { type: 'any' },
    { type: 'literal', text: '\\', ignoreCase: false },
    { type: 'literal', text: '\\', ignoreCase: false },
    { type: 'literal', text: '"', ignoreCase: false }
  ],
  found: null,
  location: {
    source: undefined,
    start: { offset: 18, line: 1, column: 19 },
    end: { offset: 18, line: 1, column: 19 }
  }
```
This is the raw value of the string node `'\\'` in the AST:
```
    hexValue: '5c',
    id: 6,
    isConstant: false,
    isLValue: false,
    isPure: true,
    kind: 'string',
    lValueRequested: false,
    nodeType: 'Literal',
    src: '154:4:0',
    typeDescriptions: {
      typeIdentifier: 't_stringliteral_731553fa98541ade8b78284229adfe09a819380dee9244baac20dd1e0aa24095',
      typeString: 'literal_string "\\"'
    },
    value: '\\'
```

**Comment by blitz-1306** [comment]
This is one of the reasons why we left TypeString parser behind. It is now used for test-only purposes. We now have [`InferType`](https://github.com/ConsenSys/solc-typed-ast/blob/63828e53551f1a61b4a71103aaa4eeab4f6d9173/src/types/infer.ts#L212) component that handles type detection.

**Comment by blitz-1306** [comment]
By using `InferType.typeOf()` on such literals you would now get following type data:
```
StringLiteralType { id: <number>, src: undefined, kind: 'string' }
```
The TypeString parser is no longer shipped within a package. So I guess we can close the issue - it is no longer relevant as package users encouraged to use `InferType` component instead.
