### ISSUE TITLE
compileSol throws error on using for `<=` and `>=`

### ISSUE THREAD

**Issue by brianlai98** [Consensys/solc-typed-ast#238]
## Environment
Mac, node v18.18.2, solo-typed-ast v17.0.02

## Scenario

1. Create sample contract, `sample.sol`

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;
type Currency is address;

using { greaterThanOrEqualTo as >=, lessThanOrEqualTo as <= } for Currency global;

function greaterThanOrEqualTo(Currency currency, Currency other) pure returns (bool) {
    return Currency.unwrap(currency) >= Currency.unwrap(other);
}
function lessThanOrEqualTo(Currency currency, Currency other) pure returns (bool) {
    return Currency.unwrap(currency) <= Currency.unwrap(other);
}
```

2. try to compile
```typescript
import { compileSol} from "solc-typed-ast";
const result = await compileSol('./sample.sol', auto')
```

## Expected behavior
Should compile successfully.

## Current behavior
`compileSol` throws an error
```
Failed parsing imports at ./sample.sol - Expected " ", ",", "/*", "//", "\t", "\x0B", "\x0C", "}", " ", "﻿", [ , , , - , , ,　], or [\n,\r, , ] but "="found.
CompileInferenceError: Failed parsing imports at ./sample.sol - Expected " ", ",", "/*", "//", "\t", "\x0B", "\x0C", "}", " ", "﻿", [ , , , - , , ,　],or [\n,\r, , ] but "=" found.
    at findAllFiles (./node_modules/.pnpm/solc-typed-ast@17.0.2_typescript@5.2.2/node_modules/solc-typed-ast/src/compile/inference/imports.ts:171:23)
    at compileSol (./infrastructure/node_modules/.pnpm/solc-typed-ast@17.0.2_typescript@5.2.2/node_modules/solc-typed-ast/src/compile/utils.ts:319:27)
```

It only seems to throw an error for `>=` and `<=`. It compiles successfully for `==`, `>`, and `<`:

this works:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

type Currency is address;

function equals(Currency currency, Currency other) pure returns (bool) {
    return Currency.unwrap(currency) == Currency.unwrap(other);
}

function greaterThan(Currency currency, Currency other) pure returns (bool) {
    return Currency.unwrap(currency) > Currency.unwrap(other);
}

function lessThan(Currency currency, Currency other) pure returns (bool) {
    return Currency.unwrap(currency) < Currency.unwrap(other);
}

using { greaterThan as >, lessThan as <, equals as == } for Currency global;
```

**Comment by blitz-1306** [comment]
Hello and thanks for your input. I guess we can go with patch release soon. I would find some time to create a pull request and check if suggested fix would be fine with the rest of the codebase. Stay tuned.

**Comment by blitz-1306** [comment]
@brianlai98 See #239. It would also take some time to create a patch PR, review and and trigger a release. I would suggest to expect the patch version during the next week.
